import { Geist, Geist_Mono } from "next/font/google";
import { Provider } from "../components/ui/provider";
import { AuthProvider } from "../contexts/AuthContext";
import { LanguageProvider } from "../contexts/LanguageContext";
import GlobalLoading from "../components/GlobalLoading";
import Header from "./componets/Header";
import Footer from "./componets/Footer";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          minHeight: '100vh',
          display: 'flex',
          flexDirection: 'column',
          margin: 0,
          padding: 0,
        }}
      >
        <Provider>
          <LanguageProvider>
            <AuthProvider>
              <GlobalLoading>
                <Header />
                <main style={{ flex: 1, display: 'flex', flexDirection: 'column' }}>
                  {children}
                </main>
                <Footer/>
              </GlobalLoading>
            </AuthProvider>
          </LanguageProvider>
        </Provider>
      </body>
    </html>
  );
}
